package models

type CATEGORY string

const (
	NIKE             CATEGORY = "NIKE"
	FINISHLINE       CATEGORY = "FINISHLINE"
	MACYS            CATEGORY = "MACYS"
	MRPORTER         CATEGORY = "MRPORTER"
	NETAPORTER       CATEGORY = "NETAPORTER"
	LUISAVIAROMA     CATEGORY = "LUISAVIAROMA"
	ADIDAS           CATEGORY = "ADIDAS"
	SNEAKERBOY       CATEGORY = "SNEAKERBOY"
	GAMESTOP         CATEGORY = "GAMESTOP"
	PACSUN           CATEGORY = "PACSUN"
	YEEZYSUPPLY      CATEGORY = "YEEZYSUPPLY"
	SUPPLYSTORE      CATEGORY = "SUPPLYSTORE"
	SSENSE           CATEGORY = "SSENSE"
	LANECRAWFORD     CATEGORY = "LANECRAWFORD"
	LOUISVUITTON     CATEGORY = "LOUISVUITTON"
	NEWBALANCE       CATEGORY = "NEWBALANCE"
	TAF              CATEGORY = "TAF"
	SNKRS            CATEGORY = "SNKRS"
	TEXASINSTRUMENTS CATEGORY = "TEXASINSTRUMENTS"
)
